server:
  port: 8888
spring:
  application:
    name: springboot-blog
#  profiles:
#    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: tsy7172139
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置druid连接池

  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制日志输出

  global-config:
    db-config:
      table-prefix: ms_ #数据库表名的前缀





